baseURL: "https://mikaelkirken.netlify.com/"
languageCode: no
DefaultContentLanguage: no
title: "Mikaelkirken Blogg"
pygmentsstyle: 'monokai'
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
params:
  DateForm: "2.1.2006"
  # DateForm: "Monday, Jan 2, 2006"